Fixed init_local_db hanging by force killing it
MOV-AI/flow-initiator pull request #143
Opened 2024-05-15 14:03 UTC by VicenteMovai

Fixed process hanging by force killing the init_local_db.

It was hanging here:
```
i_mod = importlib.import_module(mod)
```

:warning: Importing EVERY system and python package is a serious security risk, we should revise this in the future

2024-05-15 14:34 UTC, AlexFernandes-MOVAI commented on flow_initiator/tools/init_local_db.py
>      Callback.export_modules()
what if `Callback.export_modules()` hangs ?

2024-05-16 10:59 UTC, diasdm reviewed
Can we do something about the `echo "Info : initializing local DB. DONE"` which is printed before it is actually finished?

2024-05-16 13:34 UTC, AlexFernandes-MOVAI approved these changes

2024-05-16 13:40 UTC, AlexFernandes-MOVAI commented
> Can we do something about the `echo "Info : initializing local DB. DONE"` which is printed before it is actually finished?

this is not  present in this repo,  it is in container base image

2024-05-16 13:44 UTC, AlexFernandes-MOVAI requested changes
quality gate not passing

2024-05-17 11:02 UTC, AlexFernandes-MOVAI approved these changes

2024-05-17 11:02 UTC, merged