BP-1253: review ensure_process_kill() - ported from movai_classes (BP-1241)
MOV-AI/flow-initiator pull request #160
Opened 2024-10-14 10:36 UTC by andreparames

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2024-10-21 12:08 UTC, AlexFernandes-MOVAI reviewed
Difference of behavior with 2.3.1:
- sigterm signal is not catched by the node callback

Can be due to the python version ? python modules version ? or `proc.terminate()` instead of `send_signal(signal.SIGTERM)`

2024-10-21 12:08 UTC, AlexFernandes-MOVAI commented on flow_initiator/spawner/elements/process_element.py
>      async def wait(self):
Function below should be reviewed:
```
async def kill(self):
        """
        A kill function for stopping
        Returns: None
        """
        self._logger.info(
            "Spawner: Trying to terminate process({})".format(self.proc.pid)
        )
        await self.ensure_process_kill()
        
```

2024-10-21 15:37 UTC, andreparames commented
> Difference of behavior with 2.3.1:
> 
>     * sigterm signal is not catched by the node callback
> 
> 
> Can be due to the python version ? python modules version ? or `proc.terminate()` instead of `send_signal(signal.SIGTERM)`

I think my port missed the part where the actual SIGTERM was sent. It used to be sent in terminate_process(), but that doesn't exist in the new code. Instead, I made ensure_process_kill() send SIGTERM after the SIGINT (and before the SIGKILL).

2024-10-28 11:01 UTC, AlexFernandes-MOVAI requested changes
Sequence is still incorrect, SIGINT is sent before SIGTERM

```
[INFO][2024-10-28 10:58:04][node][initial_print][118]: --- Starting GD_Node with Name "sleep_task" and Template "sleep_task"
[INFO][2024-10-28 10:58:04][zmq_client][_reset][61]: ZMQ connecting DEALER to: ipc:///opt/mov.ai/comm/SpawnerServer-basic_simulator-movai.sock
[INFO][2024-10-28 10:58:04][sigterm_sleep][print_and_sleep][29]: [user_log:True|node:sleep_task|callback:sigterm_sleep] Sleeping for 60 seconds
[INFO][2024-10-28 10:58:04][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 60 remaining
[INFO][2024-10-28 10:58:05][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 59 remaining
[INFO][2024-10-28 10:58:06][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 58 remaining
[INFO][2024-10-28 10:58:07][spawner][process_transition][518]: TRANS from node: sleep_task   port: end
[INFO][2024-10-28 10:58:07][flowmonitor][get_commands][149]: load flow __UNVERSIONED__
[INFO][2024-10-28 10:58:07][process_element][kill][105]: Spawner: Trying to terminate process(1623)
[INFO][2024-10-28 10:58:07][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 57 remaining
[INFO][2024-10-28 10:58:08][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 56 remaining
[WARNING][2024-10-28 10:58:09][process_element][ensure_process_kill][179]: Sending SIGINT to node sleep_task (1623)
[INFO][2024-10-28 10:58:09][node][stop][89]: Shutting down GD Node: sleep_task
[INFO][2024-10-28 10:58:09][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 55 remaining
[WARNING][2024-10-28 10:58:09][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
[INFO][2024-10-28 10:58:09][topics][_TopicManager.__init__][1132]: topicmanager initialized
[INFO][2024-10-28 10:58:10][node][initial_print][118]: --- Starting GD_Node with Name "wait_state" and Template "wait_state"
[INFO][2024-10-28 10:58:10][zmq_client][_reset][61]: ZMQ connecting DEALER to: ipc:///opt/mov.ai/comm/SpawnerServer-basic_simulator-movai.sock
[WARNING][2024-10-28 10:58:10][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
[INFO][2024-10-28 10:58:10][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 54 remaining
[WARNING][2024-10-28 10:58:10][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
[WARNING][2024-10-28 10:58:11][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
[INFO][2024-10-28 10:58:11][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 53 remaining
[WARNING][2024-10-28 10:58:11][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
[ERROR][2024-10-28 10:58:12][process_element][ensure_process_kill][191]: Sending SIGKILL to node sleep_task (1623)
[INFO][2024-10-28 10:58:12][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 52 remaining
[WARNING][2024-10-28 10:58:12][spawner][clean_element][262]: Node: sleep_task is still running
[ERROR][2024-10-28 10:58:12][spawner][clean_element][281]: **  Node sleep_task (machine: HOST, PID: 1623) terminated with code -9  **
[INFO][2024-10-28 10:58:13][spawner][process_stop][478]: STOP flow global/Flow/_test/__UNVERSIONED__
[INFO][2024-10-28 10:58:13][process_element][kill][105]: Spawner: Trying to terminate process(1648)
[INFO][2024-10-28 10:58:13][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 51 remaining
[INFO][2024-10-28 10:58:14][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 50 remaining
```

2024-10-28 11:17 UTC, AlexFernandes-MOVAI commented
> Sequence is still incorrect, SIGINT is sent before SIGTERM
> 
> ```
> [INFO][2024-10-28 10:58:04][node][initial_print][118]: --- Starting GD_Node with Name "sleep_task" and Template "sleep_task"
> [INFO][2024-10-28 10:58:04][zmq_client][_reset][61]: ZMQ connecting DEALER to: ipc:///opt/mov.ai/comm/SpawnerServer-basic_simulator-movai.sock
> [INFO][2024-10-28 10:58:04][sigterm_sleep][print_and_sleep][29]: [user_log:True|node:sleep_task|callback:sigterm_sleep] Sleeping for 60 seconds
> [INFO][2024-10-28 10:58:04][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 60 remaining
> [INFO][2024-10-28 10:58:05][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 59 remaining
> [INFO][2024-10-28 10:58:06][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 58 remaining
> [INFO][2024-10-28 10:58:07][spawner][process_transition][518]: TRANS from node: sleep_task   port: end
> [INFO][2024-10-28 10:58:07][flowmonitor][get_commands][149]: load flow __UNVERSIONED__
> [INFO][2024-10-28 10:58:07][process_element][kill][105]: Spawner: Trying to terminate process(1623)
> [INFO][2024-10-28 10:58:07][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 57 remaining
> [INFO][2024-10-28 10:58:08][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 56 remaining
> [WARNING][2024-10-28 10:58:09][process_element][ensure_process_kill][179]: Sending SIGINT to node sleep_task (1623)
> [INFO][2024-10-28 10:58:09][node][stop][89]: Shutting down GD Node: sleep_task
> [INFO][2024-10-28 10:58:09][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 55 remaining
> [WARNING][2024-10-28 10:58:09][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
> [INFO][2024-10-28 10:58:09][topics][_TopicManager.__init__][1132]: topicmanager initialized
> [INFO][2024-10-28 10:58:10][node][initial_print][118]: --- Starting GD_Node with Name "wait_state" and Template "wait_state"
> [INFO][2024-10-28 10:58:10][zmq_client][_reset][61]: ZMQ connecting DEALER to: ipc:///opt/mov.ai/comm/SpawnerServer-basic_simulator-movai.sock
> [WARNING][2024-10-28 10:58:10][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
> [INFO][2024-10-28 10:58:10][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 54 remaining
> [WARNING][2024-10-28 10:58:10][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
> [WARNING][2024-10-28 10:58:11][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
> [INFO][2024-10-28 10:58:11][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 53 remaining
> [WARNING][2024-10-28 10:58:11][process_element][ensure_process_kill][179]: Sending SIGTERM to node sleep_task (1623)
> [ERROR][2024-10-28 10:58:12][process_element][ensure_process_kill][191]: Sending SIGKILL to node sleep_task (1623)
> [INFO][2024-10-28 10:58:12][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 52 remaining
> [WARNING][2024-10-28 10:58:12][spawner][clean_element][262]: Node: sleep_task is still running
> [ERROR][2024-10-28 10:58:12][spawner][clean_element][281]: **  Node sleep_task (machine: HOST, PID: 1623) terminated with code -9  **
> [INFO][2024-10-28 10:58:13][spawner][process_stop][478]: STOP flow global/Flow/_test/__UNVERSIONED__
> [INFO][2024-10-28 10:58:13][process_element][kill][105]: Spawner: Trying to terminate process(1648)
> [INFO][2024-10-28 10:58:13][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 51 remaining
> [INFO][2024-10-28 10:58:14][sigterm_sleep][print_and_sleep][31]: [user_log:True|node:sleep_task|callback:sigterm_sleep] (1639)Sleeping for 1s, 50 remaining
> ```

@andreparames  did you investigate the fact that the children processes do not receive the sigterm in comparison to 2.3.1 ?

2024-11-13 10:04 UTC, merged