Feature bp 741 replace movai classes with flow initiator
MOV-AI/flow-initiator pull request #29
Opened 2022-09-21 12:52 UTC by erezz-mov-ai

jira:
https://movai.atlassian.net/browse/BP-741?atlOrigin=eyJpIjoiZDVkNzNlMDZkMTIwNDcwNGFmMDAwMmIwNTk5MWQwMDEiLCJwIjoiaiJ9
- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-09-22 07:23 UTC, Mograbi requested changes

2022-09-22 07:23 UTC, Mograbi commented on flow_initiator/__main__.py
> +from flow_initiator import main
this need to be tested

2022-09-22 07:23 UTC, Mograbi commented on flow_initiator/spawner/async_movaicore.py
> +from flow_initiator.spawner.async_spawner import Spawner
when it was relative it does not import all of the inits in the whole path
so I think it's better to preserve the old relative way of import

2022-09-22 09:32 UTC, erezz-mov-ai commented on flow_initiator/spawner/flowmonitor.py
>              return []
restore print exception

2022-09-22 14:45 UTC, erezz-mov-ai commented on flow_initiator/spawner/async_movaicore.py
> +from flow_initiator.spawner.async_spawner import Spawner
done

2022-09-26 08:05 UTC, Mograbi approved these changes

2022-09-28 09:52 UTC, Mograbi approved these changes

2022-09-28 09:52 UTC, merged