Feat: changes for 2.4.0 release
MOV-AI/flow-initiator pull request #33
Opened 2022-11-10 22:31 UTC by erezz-mov-ai

#32 

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-11-14 08:47 UTC, engdorm approved these changes

2022-11-16 08:19 UTC, engdorm commented
@AlexFernandes-MOVAI added the missing reqs 
please review

2022-11-16 11:18 UTC, diasdm requested changes

2022-11-16 11:18 UTC, diasdm commented on tox.ini
> +setenv =
Let's discuss this is today's meeting

2022-11-16 16:27 UTC, AlexFernandes-MOVAI commented on tox.ini
> +setenv =
As agreed, I have put integration repo instead of experimental

2022-11-16 16:28 UTC, AlexFernandes-MOVAI commented
need gd-node to be released first:
`ERROR: Could not find a version that satisfies the requirement gd-node==1.0.1.0 (from flow-initiator) (from versions: 1.0.0.1, 1.0.0.2, 1.0.0.3, 1.0.0.4, 1.0.0.5, 1.0.0.6, 1.0.0.7, 1.0.0.8, 1.0.0.9)
ERROR: No matching distribution found for gd-node==1.0.1.`

2022-11-30 09:51 UTC, AlexFernandes-MOVAI requested changes
small changes requested

2022-11-30 09:51 UTC, AlexFernandes-MOVAI commented on setup.py
>      description="Dummy description",
Please change `dummy description`

2022-11-30 09:51 UTC, AlexFernandes-MOVAI commented on .bumpversion.cfg
>  	[SKIP] Automatic version bump {current_version} -> {new_version}
please change [SKIP] by [skip actions]

2022-12-20 17:21 UTC, merged