creating new release for 2.4.0
MOV-AI/flow-initiator pull request #34
Opened 2022-11-16 14:35 UTC by erezz-mov-ai

creating new release for 2.4.0

2022-11-16 14:45 UTC, engdorm requested changes
I'm not sure bout the deletion requirements.txt

2022-11-16 16:47 UTC, AlexFernandes-MOVAI reviewed
OK, so here you create a branch for the future 2.4.0 release :
- main/dev : hold the 2.3.x release line
- develop/2.4.0 and releases/2.4.0 : hold the 2.4.x release line
This is valid, just make sure to:
- communicate about this
- merge back develop/2.4.0 and releases/2.4.0 as soon as 2.4.0 becomes the official latest version

2022-11-16 16:47 UTC, AlexFernandes-MOVAI commented on flow_initiator/spawner/flowmonitor.py
> +            output = ["gd_node"]
so, this `gd_node` binary needs to be in the path  ?

2022-11-16 16:51 UTC, AlexFernandes-MOVAI requested changes
please align the version number of branches and modules:
- if branches are called something/2.4.0, the modules should be versioned 2.4.x

2022-11-17 09:30 UTC, engdorm commented on flow_initiator/spawner/flowmonitor.py
> +            output = ["gd_node"]
the gd_node will be an endpoint inside the gd-node python package

2022-11-17 09:37 UTC, erezz-mov-ai commented on flow_initiator/spawner/flowmonitor.py
> +            output = ["gd_node"]
yes it was added to the setup.py as an entry point

2022-11-17 09:39 UTC, erezz-mov-ai commented
> I'm not sure bout the deletion requirements.txt



>

2022-11-17 09:41 UTC, erezz-mov-ai commented
> I'm not sure bout the deletion requirements.txt

the requirements are mentioned inside the setup.py, so requirements.txt is not longer needed.
also the pipline don't know how to handle it.

2022-11-17 12:23 UTC, erezz-mov-ai commented on flow_initiator/spawner/flowmonitor.py
> +            output = ["gd_node"]
yes we must extend update PATH env to include:
/opt/mov.ai/.local/bin

2022-11-20 08:12 UTC, engdorm approved these changes

2022-11-22 09:27 UTC, merged