Feature/bp 255/rebase on 2.4.0
MOV-AI/flow-initiator pull request #39
Opened 2022-12-28 08:23 UTC by engdorm

flow-init feature

2023-01-02 12:30 UTC, Mograbi requested changes

2023-01-26 14:25 UTC, AlexFernandes-MOVAI requested changes

2023-01-26 14:25 UTC, AlexFernandes-MOVAI commented on setup.py
> +    "docker==5.0.3"
We should use at least docker==6.0.0

2023-05-07 09:13 UTC, engdorm commented on flow_initiator/spawner/container_tools/docker_base_manager.py
> +from movai_core_shared.envvars import DOCKER_REGISTRY
there is a branch I need to merge

2023-05-07 10:24 UTC, engdorm commented on flow_initiator/spawner/async_spawner.py
> +                    ros2_lifecycle_nodes_to_activate.append(lc_node["node"])
maybe 
it old code that we need to check

2023-10-26 08:55 UTC, engdorm commented on flow_initiator/spawner/flowmonitor.py
> +            LOGGER.error()
need to add e

2023-10-26 08:56 UTC, engdorm commented on flow_initiator/spawner/flowmonitor.py
> +            LOGGER.error()
need to check why did I removed it

2023-12-12 11:34 UTC, closed without merging